name: Tests

on:
  push:

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: release-it Tests
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: Setup node.js
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 12

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Test running action
      id: test-run
      uses: ./
      with:
        json-opts: '{"dry-run": true, "git": {"requireCleanWorkingDir": false}}'
