name: Build

on:
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: release-it Build
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0

    - name: Setup node.js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12

    - name: Install dependencies
      run: npm ci

    - name: Lint & Fix
      run: npm run lint-fix

    - name: Build
      run: npm run build

    - uses: EndBug/add-and-commit@v4
      with:
        message: Auto rebuild
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
