on:
  issue_comment:
    types: [created]

name: Automatic Rebase

jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest

    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '@TRW-bot rebase') && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER')

    steps:

    - name: Checkout the latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.5
      env:
        GITHUB_TOKEN: ${{ secrets.AUTO_PAT }}
