name: Release

on:
  push:
    branches:
      - master
      - release
      - RIT-39-auto-resolve-build-output-conflicts

jobs:
  release-action:
    runs-on: ubuntu-latest
    name: Release release-it action
    steps:

    - name: Setup node.js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12

    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: npm ci

    - name: Bump version
      id: bump-version
      uses: ./
      with:
        github-token: ${{ secrets.AUTO_PAT }}
        github-username: TRW-bot
        git-user-name: TheRealWaldo Bot
        git-user-email: TRW-bot@inwr.com
        create-branch: release
        auto-resolve-command: npm run build && git add dist/**

    - name: Create pull request
      uses: repo-sync/pull-request@v2.3
      with:
        github_token: ${{ secrets.AUTO_PAT }}
        source_branch: release
