name: Release

on:
  push:
    branches:
      - master

jobs:
  release-action:
    runs-on: ubuntu-latest
    name: release-it Tests
    steps:

    - name: Setup node.js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12

    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        ref: master

    - name: Install dependencies
      run: npm ci

    - name: Bump version
      id: bump-version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: ./

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        base: master
