name: Release

on:
  push:
    branches:
      - master

jobs:
  release-action:
    runs-on: ubuntu-latest
    name: release-it Tests
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Setup node.js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12

    - name: Install dependencies
      run: npm ci

    - name: Test running action
      id: test-run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: ./
