name: Release

on:
  push:
    branches:
      - master

jobs:
  release-action:
    runs-on: ubuntu-latest
    name: Release release-it action
    steps:

    - name: Setup node.js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12

    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Install dependencies
      run: npm ci

    - name: Bump version
      id: bump-version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: ./
      with:
        create-branch: release

    - name: Create pull request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: release
        pr_draft: true
